apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
    labels:
      app: dotnet-api

      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: codecraftacr.azurecr.io/dotnet-api:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-auth
